// Write a function that uses reduce to calculate the total revenue generated by the store from all the orders. Assume that the revenue from each order is the sum of the prices of all the items in the order.

const orders = [
  { id: 1, items: [{ name: 'book', price: 10 }, { name: 'pen', price: 2 }] },
  { id: 2, items: [{ name: 'shirt', price: 20 }, { name: 'pants', price: 30 }] },
  { id: 3, items: [{ name: 'hat', price: 15 }, { name: 'socks', price: 5 }] }
]

const getTotalrevenue = orders => orders.reduce((revenue, {items}) => {
    return revenue + items.reduce((total, item) => total + item.price, 0);
},0)

console.log(getTotalrevenue(orders))