// Write a function that uses reduce to calculate the total revenue generated by the company from all the sales. Assume that the revenue from each sale is the product of the amount and price.

const sales = [
  { product: 'apple', amount: 100, price: 1 },
  { product: 'banana', amount: 200, price: 0.5 },
  { product: 'orange', amount: 300, price: 0.75 },
  { product: 'grape', amount: 400, price: 0.4 },
];

const getTotalRevenue = sales => sales.reduce((totalRevenue, {amount, price}) => {
    return totalRevenue + (amount * price);
}, 0);

console.log(getTotalRevenue(sales)); // 585